# generated by datamodel-codegen:
#   filename:  confluent-cloud-api.spec.json
#   timestamp: 2022-11-30T11:44:44+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Extra

from . import ApiVersion, Id, Kind, ResourceMetadata, SpecElement


class Byok(BaseModel):
    api_version: Optional[ApiVersion] = None
    id: Optional[str] = None
    kind: Optional[Kind] = None
    related: Optional[str] = None
    resource_name: Optional[str] = None


class Config(BaseModel):
    class Config:
        extra = Extra.allow

    cku: Optional[int] = None
    encryption_key: Optional[str] = None
    kind: Optional[str] = None
    zones: Optional[List[str]] = None


class Status(BaseModel):
    class Config:
        extra = Extra.forbid

    phase: Optional[str] = None
    cku: Optional[int] = None


class Spec(BaseModel):
    class Config:
        extra = Extra.forbid

    api_endpoint: Optional[str] = None
    availability: Optional[str] = None
    cloud: Optional[str] = None
    byok: Optional[Byok] = None
    config: Optional[Config] = None
    display_name: Optional[str] = None
    region: Optional[str] = None
    kafka_bootstrap_endpoint: Optional[str] = None
    http_endpoint: Optional[str] = None
    environment: Optional[SpecElement] = None
    network: Optional[SpecElement] = None


class SpecModel(BaseModel):
    class Config:
        extra = Extra.forbid

    api_version: Optional[ApiVersion] = None
    id: Optional[Id] = None
    kind: Optional[Kind] = None
    metadata: Optional[ResourceMetadata] = None
    spec: Optional[Spec] = None
    status: Optional[Status] = None
